=== Wisiwy/Ev2_XML_Practicas/UD03_Xml-Ddt_PRACTICAS/t3p3_GomezR_IN1WV/t3p3_GomezR_Daw.dtd
<!ELEMENT ticket (datosTicket,datosComercio,datosCompra)>
<!ATTLIST ticket cod NMTOKEN #REQUIRED>
<!ELEMENT datosTicket (fecha,hora,precioTotal,formaPago,imgticket)>
<!ELEMENT fecha (dia,mes,ano)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT precioTotal (precioSinIva,pvp)>
<!ATTLIST precioTotal moneda NMTOKEN #REQUIRED>
<!ELEMENT precioSinIva (#PCDATA)>
<!ELEMENT pvp (#PCDATA)>
<!ATTLIST pvp iva CDATA #REQUIRED>
<!ELEMENT formaPago (tarjeta)>
<!ATTLIST formaPago tipo NMTOKEN #REQUIRED>
<!ELEMENT tarjeta (numero,cliente)>
<!ATTLIST tarjeta tipo NMTOKEN #REQUIRED>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT cliente (#PCDATA)>
<!ELEMENT imgticket EMPTY>
<!ATTLIST imgticket nombre NMTOKEN #REQUIRED>
<!ATTLIST imgticket formato NMTOKEN #REQUIRED>
<!ELEMENT datosComercio (nombre,dir,cif,telf)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT telf (#PCDATA)>
<!ELEMENT datosCompra (lineaCompra+)>
<!ELEMENT lineaCompra (nombre,cantidad,precio,pvpLinea)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio iva CDATA #REQUIRED>
<!ELEMENT pvpLinea (#PCDATA)>
<!ENTITY G "21">

=== Wisiwy/Ev2_XML_Practicas/UD03_Xml-Ddt/t3p3_GomezR_IN1WV/t3p3_GomezR_Daw.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ticket SYSTEM "t3p3_GomezR_Daw.dtd" [
    <!ENTITY G "entity-value">
]>
<ticket cod="t00037">
    <datosTicket>
        <fecha>
            <dia>22</dia>
            <mes>12</mes>
            <ano>2018</ano>
        </fecha>
        <hora>12:23:12</hora>
        <precioTotal moneda="Euro">
            <precioSinIva>10,5</precioSinIva>
            <pvp iva= "&G;">12,75</pvp>
        </precioTotal>
        <formaPago tipo="Tarjeta">
            <tarjeta tipo="Visa">
                <numero>************1474</numero>
                <cliente>Aniceto Cartapeto</cliente>
            </tarjeta>
        </formaPago>
        <imgticket nombre="ticket12" formato="jpg" />
    </datosTicket>
    <datosComercio>
        <nombre>El Rincon</nombre>
        <dir>C/ Santander NÂº12</dir>
        <cif>989889A</cif>
        <telf>976121212</telf>
    </datosComercio>
    <datosCompra>
        <lineaCompra>
            <nombre>Barra Pan</nombre>
            <cantidad>10</cantidad>
            <precio iva= "&G;">1</precio>
            <pvpLinea>12,1</pvpLinea>
        </lineaCompra>
        <lineaCompra>
            <nombre>Palmera</nombre>
            <cantidad>1</cantidad>
            <precio iva= "&G;">0.5</precio>
            <pvpLinea>0.65</pvpLinea>
        </lineaCompra>
    </datosCompra>
</ticket>
