=== Wisiwy/Ev2_XML_Practicas/UD03_Xml-Ddt_PRACTICAS/t3p4_GomezR_IN1WV/Excursion_Original.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="viaje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fecha" type="xs:date" />
                <xs:element name="hora" type="xs:time" />
                <xs:element name="precio" type="xs:double" />
                <xs:element name="participantes" maxOccurs="70">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="participante" maxOccurs="70">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre">
                                            <xs:simpleType>
                                                <!-- Valor max nombre -->
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="15" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="apellido">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <!-- Valor max apellido -->
                                                    <xs:maxLength value="20" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="nif">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <!-- Patron DNI -->
                                                    <xs:pattern value="[0-9]{9}[A-Z]" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="fechaNac" type="xs:date" />
                                        <!-- CHOICE: Alumno y profesor -->
                                        <xs:choice>
                                            <!-- PROFESOR -->
                                            <xs:element name="profesor">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="mail">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:pattern
                                                                        value="[.]+[@][A-Z,a-z]+[.com]" />

                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:element>
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                            <!-- ALUMNO -->
                                            <xs:element name="alumno">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="telfPadre" minOccurs="0"
                                                            maxOccurs="1">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:integer">
                                                                    <xs:pattern value="[0-9]{9}" />
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:element>
                                                        <xs:element name="telfMadre" minOccurs="0"
                                                            maxOccurs="1">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:integer">
                                                                    <xs:pattern value="[0-9]{9}" />
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:element>
                                                        <xs:element name="grupo" type="xs:string" />
                                                        <xs:element name="humor" type="xs:boolean" />
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:choice>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Wisiwy/Ev2_XML_Practicas/UD03_Xml-Ddt_PRACTICAS/t3p4_GomezR_IN1WV/Excursion_Original.xml
<?xml version="1.0" encoding="UTF-8"?>
<viaje xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Excursion_Original.xsd">
	<fecha>2019-01-31</fecha>
	<hora>06:30:00</hora>
	<precio>25.0</precio>
	<participantes>
		<participante>
			<nombre>Juan Ignacio</nombre>
			<apellido>Farray</apellido>
			<nif>00000000A</nif>
			<fechaNac>1985-10-10</fechaNac>
			<profesor>
				<telf>655444444</telf>
				<mail>jif@losenlaces.com</mail>
			</profesor>
		</participante>
		<participante>
			<nombre>Marco</nombre>
			<apellido>Aurelio</apellido>
			<nif>11111111B</nif>
			<fechaNac>2005-05-05</fechaNac>
			<alumno>
				<telfPadre>555222222</telfPadre>
				<telfMadre>555666666</telfMadre>
				<grupo>IN1</grupo>
				<humor>true</humor>
			</alumno>
		</participante>
	</participantes>
</viaje>
